In [1]:
import requests
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import pandas as pd

In [4]:
import csv

stock_codes = []
with open('bist100kod.csv', newline='') as inputfile:
    for row in csv.reader(inputfile):
        results.append(row[0])

print(results)

In [ ]:
df=pd.DataFrame()
#stock_codes=['TUKAS','GARAN','YKBNK']
for code in stock_codes:
    
    date = requests.get(f"https://www.oyakyatirim.com.tr/Equity/GetHistoricalEquityData?mode=2&code={code}")
    date = np.array(eval(date.text))[:,0]
    
    vals = requests.get(f"https://www.oyakyatirim.com.tr/Equity/GetHistoricalEquityData?mode=2&code={code}")
    vals = np.array(eval(vals.text))[:,1]
    
    df['DATE']=date
    df[code]=vals
df.to_excel(r'C:\Users\Kaan\Desktop\data\output.xlsx', index = False)

In [5]:
df

            DATE  AFYON  AKBNK   AKSA  AKSEN  ALGYO  ALARK  ALBRK
0   1.604275e+12   4.20   4.82   8.45   6.16  16.69   6.20   1.61
1   1.604362e+12   4.17   5.04   8.23   6.57  16.94   6.17   1.64
2   1.604448e+12   4.22   5.00   8.41   6.78  17.04   6.17   1.64
3   1.604534e+12   4.26   5.01   8.68   6.99  17.35   6.15   1.70
4   1.604621e+12   4.31   5.02   9.01   7.14  17.42   6.23   1.69
5   1.604880e+12   4.41   5.38   9.32   7.05  17.62   6.56   1.76
6   1.604966e+12   4.61   5.66   9.31   7.21  18.30   6.50   1.76
7   1.605053e+12   4.55   6.22   9.41   7.41  18.20   6.77   1.82
8   1.605139e+12   4.33   6.24   9.94   7.37  17.12   6.48   1.73
9   1.605226e+12   4.42   6.31   9.91   7.34  17.15   6.64   1.76
10  1.605485e+12   4.50   6.31   9.91   7.24  17.12   6.62   1.76
11  1.605571e+12   4.27   5.99   9.91   7.24  16.60   6.43   1.69
12  1.605658e+12   4.38   6.27  10.02   7.20  16.75   6.51   1.76
13  1.605744e+12   4.41   6.47  10.49   7.26  16.99   6.63   1.76
14  1.605830e+12   4.52   6.50  10.76   7.17  17.05   6.64   1.77
15  1.606090e+12   4.49   6.26  10.71   7.02  17.66   6.49   1.74
16  1.606176e+12   4.56   6.28  11.00   7.10  17.51   6.49   1.75
17  1.606262e+12   4.48   6.30  10.73   7.05  18.37   6.40   1.72
18  1.606349e+12   4.50   6.45  10.81   7.04  18.11   6.32   1.73
19  1.606435e+12   4.52   6.38  10.63   7.12  18.61   6.39   1.71
20  1.606694e+12   4.32   6.02  10.69   7.00  19.69   6.32   1.70